[theme]
# Gebruik Rijk Zwart voor tekst
textColor = "#030203"
# Gebruik Wit voor achtergronden
backgroundColor = "#FFFFFF"
# Gebruik de Goud-accentkleur voor interactieve elementen (buttons, links)
primaryColor = "#AE9A64"
secondaryBackgroundColor = "#F0F2F6"
font = "sans serif"
